name: Pin Actions to Commit Hashes

# 触发条件：工作流文件变更时自动运行
on:
  push:
    branches: [ multi ]  # 监听主要开发分支
    paths: [ '.github/workflows/**.yml' ]  # 仅当工作流文件修改时触发
  pull_request:
    branches: [ multi ]
    paths: [ '.github/workflows/**.yml' ]

permissions:
  contents: write  # 允许工作流推送修改到仓库
  pull-requests: write  # 允许创建PR（如需）

jobs:
  pin-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab885d02cd575d907c9e59b6  # 固定哈希
        with:
          fetch-depth: 0  # 拉取完整历史，方便后续提交

      - name: Install pinact
        run: |
          # 安装pinact（使用官方二进制，避免Go环境依赖）
          curl -sL https://github.com/pinact-io/pinact/releases/latest/download/pinact-linux-amd64 -o /usr/local/bin/pinact
          chmod +x /usr/local/bin/pinact
          pinact --version  # 验证安装

      - name: Fix action versions (pin to commit hashes)
        run: pinact fix .github/workflows/*.yml  # 自动替换版本为哈希

      - name: Verify fixes
        run: pinact verify .github/workflows/*.yml  # 校验替换结果是否有效

      - name: Commit changes (if any)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .github/workflows/*.yml
          git commit -m "Auto-pin actions to commit hashes" || echo "No changes to commit"
          git push origin ${{ github.ref }}  # 推送修改到当前分支

      # 可选：若不希望直接推送到主分支，可创建PR（更安全）
      # - name: Create PR for changes
      #   if: github.event_name == 'pull_request'
      #   uses: actions/create-pull-request@c5a7806660adbe1734a63d7c078f1cc17a0486
      #   with:
      #     title: "Auto-fix: Pin actions to commit hashes"
      #     body: "This PR fixes action versions to use commit hashes for security."
