name: Update Basic Rules & Mihomo
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches: [ "basic" ]
    paths:
      - 'data/python/**'
      - 'data/mod/**'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      DATA_DIR: ${{ github.workspace }}/data
      PYTHON_SCRIPTS: ${{ github.workspace }}/data/python
      MIHOMO_BIN: ${{ github.workspace }}/data/mihomo-tool
      MAIN_BRANCH: basic

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.MAIN_BRANCH }}

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Detect changed files
        id: changes
        uses: tj-actions/changed-files@v42
        with:
          files: |
            ${{ env.PYTHON_SCRIPTS }}/**
            ${{ env.DATA_DIR }}/mod/**

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 pyyaml
          # 添加脚本实际需要的其他包

      # 其余步骤保持不变...
      - name: Update Mihomo (if version mismatch)
        id: mihomo
        run: |
          LATEST_VERSION=$(curl -sL https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.tag_name' | sed 's/v//')
          echo "Latest version: $LATEST_VERSION"
          
          if [ -f "${{ env.MIHOMO_BIN }}" ]; then
            CURRENT_VERSION=$("${{ env.MIHOMO_BIN }}" -v 2>/dev/null | awk '{print $2}' | sed 's/v//' || echo "0.0.0")
          else
            CURRENT_VERSION="0.0.0"
          fi
          echo "Current version: $CURRENT_VERSION"
          
          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
            echo "Updating Mihomo from v$CURRENT_VERSION to v$LATEST_VERSION"
            mkdir -p $(dirname "${{ env.MIHOMO_BIN }}")
            curl -sL "https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-linux-amd64-v${LATEST_VERSION}.gz" | gzip -d > "${{ env.MIHOMO_BIN }}"
            chmod +x "${{ env.MIHOMO_BIN }}"
            echo "mihomo_updated=true" >> $GITHUB_OUTPUT
          else
            echo "Mihomo is up-to-date (v$LATEST_VERSION)"
            echo "mihomo_updated=false" >> $GITHUB_OUTPUT
          fi
          echo "$LATEST_VERSION" > "${{ env.DATA_DIR }}/.mihomo_version"
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Process basic rules
        if: steps.changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        run: |
          python ${{ env.PYTHON_SCRIPTS }}/dl.py
          python ${{ env.PYTHON_SCRIPTS }}/merge.py
          python ${{ env.PYTHON_SCRIPTS }}/filter-dns.py
        continue-on-error: true

      - name: Generate Mihomo native rules
        if: steps.changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        run: python ${{ env.PYTHON_SCRIPTS }}/mihomo.py

      - name: Update docs (Title & README)
        if: steps.changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        run: python ${{ env.PYTHON_SCRIPTS }}/title.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          if [ "${{ steps.mihomo.outputs.mihomo_updated }}" = "true" ]; then
            git commit -m "Basic rules updated + Mihomo v${{ env.LATEST_VERSION }} at $(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')（北京时间）"
          else
            git commit -m "Basic rules updated at $(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')（北京时间）"
          fi || echo "No changes to commit"

      - name: Push changes to basic branch
        run: |
          for i in 1 2 3; do
            git pull --rebase origin ${{ env.MAIN_BRANCH }}
            git push origin ${{ env.MAIN_BRANCH }} && break || sleep 5
          done

      - name: Cleanup old workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0