name: Update Multi Rules with SmartDNS
on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  push:
    branches: [ "multi" ]
    paths:
      - 'data/mod/**'
      - 'data/rules.txt'

permissions:
  contents: write
  actions:write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      DATA_DIR: ${{ github.workspace }}/data
      PYTHON_SCRIPTS: ${{ github.workspace }}/data/python
      MIHOMO_BIN: ${{ github.workspace }}/data/mihomo-tool
      MAIN_BRANCH: multi
      CACHE_DIR: ${{ github.workspace }}/data/cache
      TEMP_DIR: ${{ github.workspace }}/tmp
      SMARTDNS_PORT: 5353
      SMARTDNS_RULE_SOURCES: ${{ github.workspace }}/data/smartdns_sources.txt

    steps:
      # 1. 拉取代码（multi分支）
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.MAIN_BRANCH }}

      # 2. 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 缓存Python依赖
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. 安装系统依赖
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq moreutils dnsutils

      # 5. 安装Python依赖
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install aiohttp aiodns psutil xxhash maxminddb pyyaml requests chardet adblockparser IPy pytz pybloom-live aiofiles

      # 6. 创建必要的目录
      - name: Create directories
        run: |
          mkdir -p ${{ env.DATA_DIR }}/filter
          mkdir -p ${{ env.DATA_DIR }}/mod/backups
          mkdir -p ${{ env.DATA_DIR }}/smartdns
          mkdir -p ${{ env.CACHE_DIR }}
          mkdir -p ${{ env.TEMP_DIR }}
          mkdir -p ${{ env.DATA_DIR }}/sources

      # 7. 检测文件变更
      - name: Detect changed files
        id: changes
        uses: tj-actions/changed-files@v42
        with:
          files: |
            data/mod/**
            data/rules.txt

      # 8. 下载SmartDNS（使用缓存）
      - name: Install SmartDNS with cache
        id: cache-smartdns
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/smartdns
          key: ${{ runner.os }}-smartdns-${{ hashFiles('**/smartdns-version.txt') }}
          restore-keys: |
            ${{ runner.os }}-smartdns-

      # 9. 如果没有缓存，下载SmartDNS
      - name: Download SmartDNS
        if: steps.cache-smartdns.outputs.cache-hit != 'true'
        run: |
          echo "获取SmartDNS最新版本信息..."
          API_URL="https://api.github.com/repos/pymumu/smartdns/releases/latest"
          LATEST_RELEASE=$(curl -sL $API_URL)
          
          if echo "$LATEST_RELEASE" | jq -e '.message' | grep -q "Not Found"; then
              echo "错误：未找到仓库或发布版本"
              exit 1
          fi

          RELEASE_TAG=$(echo "$LATEST_RELEASE" | jq -r '.tag_name // empty')
          if [ -z "$RELEASE_TAG" ]; then
              echo "错误：无法获取发布标签"
              exit 1
          fi
          echo "最新版本: $RELEASE_TAG"
          echo "$RELEASE_TAG" > ${{ github.workspace }}/smartdns-version.txt

          DOWNLOAD_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | test("smartdns-x86_64$")) | .browser_download_url' | head -n 1)
          
          if [ -z "$DOWNLOAD_URL" ]; then
              DOWNLOAD_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | contains("x86_64")) | .browser_download_url' | head -n 1)
          fi
          
          if [ -z "$DOWNLOAD_URL" ]; then
              echo "错误：未找到x86_64架构的二进制文件"
              exit 1
          fi
          
          echo "下载链接: $DOWNLOAD_URL"
          curl -L -o "/usr/local/bin/smartdns" --progress-bar "$DOWNLOAD_URL"
          sudo chmod +x "/usr/local/bin/smartdns"
          echo "SmartDNS安装完成"

      # 10. 并行下载规则
      - name: Download rules in parallel
        run: |
          echo "开始并行下载规则..."
          python ${{ env.PYTHON_SCRIPTS }}/dl.py &
          python ${{ env.PYTHON_SCRIPTS }}/dl_smartdns.py &
          wait
          echo "规则下载完成"

      # 11. 运行merge.py（广告规则合并去重）
      - name: Run merge.py
        run: |
          echo "开始合并广告规则..."
          python ${{ env.PYTHON_SCRIPTS }}/merge.py
          echo "广告规则合并完成"

      # 12. 清理临时生成的adblock和allow文件
      - name: Cleanup temporary filter files
        run: |
          cd ${{ env.DATA_DIR }}/filter
          echo "清理临时文件..."
          for file in adblock*.txt; do
            if [ "$file" != "adblock_filter.txt" ]; then
              echo "删除临时文件: $file"
              rm -f "$file"
            fi
          done
          for file in allow*.txt; do
            if [ "$file" != "allow.txt" ]; then
              echo "删除临时文件: $file"
              rm -f "$file"
            fi
          done
          echo "临时文件清理完成"

      # 13. 运行SmartDNS规则清理器（带超时和重试）
      - name: Run SmartDNS Rule Cleaner
        run: |
          echo "开始清理SmartDNS规则..."
          timeout 600s python ${{ env.PYTHON_SCRIPTS }}/filter_cleaner.py || \
          (echo "第一次运行超时，重试..." && timeout 1200s python ${{ env.PYTHON_SCRIPTS }}/filter_cleaner.py)
          echo "SmartDNS规则清理完成"
        env:
          MAX_WORKERS: 8
          DNS_WORKERS: 30
          BATCH_SIZE: 500
          MAX_MEMORY_PERCENT: 80
          DNS_TIMEOUT: 8
          DNS_RETRIES: 2
          USE_SMARTDNS: "true"
          PROCESS_SMARTDNS_RULES: "true"

      # 14. 并行生成多格式规则
      - name: Generate multi-format rules in parallel
        run: |
          echo "开始生成多格式规则..."
          python ${{ env.PYTHON_SCRIPTS }}/filter_adg.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_adh.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_adp.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_pihole.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_hosts.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_ubo.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_clash.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_mihomo.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_smartdns.py &
          wait
          echo "多格式规则生成完成"

      # 15. 更新文档
      - name: Update documentation
        run: |
          echo "更新文档..."
          python ${{ env.PYTHON_SCRIPTS }}/title.py
          python ${{ env.PYTHON_SCRIPTS }}/readme.py
          echo "文档更新完成"

      # 16. 统一清理步骤
      - name: Unified cleanup process
        run: |
          echo "开始统一清理..."
          # 清理备份文件
          BACKUP_DIR="${{ env.DATA_DIR }}/filter/backups"
          if [ -d "$BACKUP_DIR" ]; then
            echo "清理备份文件..."
            for type in adblock allow; do
              echo "处理 $type 类型的备份文件..."
              files=$(find "$BACKUP_DIR" -type f -name "${type}_filter_backup_*.txt" -printf '%T@ %p\n' | sort -nr)
              if [ -n "$files" ]; then
                count=$(echo "$files" | wc -l)
                echo "找到 $count 个 $type 备份文件"
                if [ $count -gt 1 ]; then
                  echo "$files" | tail -n +2 | cut -d' ' -f2- | xargs -r rm -f
                  echo "已删除 $((count-1)) 个旧的 $type 备份文件"
                fi
              fi
            done
          fi
          
          # 清理临时目录
          echo "清理临时目录..."
          rm -rf ${{ env.TEMP_DIR }}
          echo "统一清理完成"

      # 17. 提交变更
      - name: Commit changes
        id: commit
        run: |
          echo "准备提交变更..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          
          # 确保不添加临时文件
          git reset -- ${{ env.DATA_DIR }}/filter/adblock[0-9]*.txt
          git reset -- ${{ env.DATA_DIR }}/filter/allow[0-9]*.txt
          
          if git diff --staged --quiet; then
            echo "没有变更需要提交"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            git commit -m "SmartDNS规则更新: [$(date +'%Y-%m-%d %H:%M:%S') UTC+8]"
            echo "变更已提交"
          fi

      # 18. 推送变更
      - name: Push changes
        if: steps.commit.outputs.has_changes == 'true'
        run: |
          echo "开始推送变更..."
          for i in 1 2 3; do
            git pull --rebase origin ${{ env.MAIN_BRANCH }}
            git push origin ${{ env.MAIN_BRANCH }} && break || sleep 5
          done
          echo "变更已推送"

      # 19. 创建工作流摘要
      # 19. 创建工作流摘要
      - name: Create workflow summary
         if: always()
         run: |
           echo "## 工作流运行摘要" >> $GITHUB_STEP_SUMMARY
           echo "- 运行状态: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
           echo "- 变更提交: ${{ steps.commit.outputs.has_changes }}" >> $GITHUB_STEP_SUMMARY
           echo "## 详细日志" >> $GITHUB_STEP_SUMMARY
           echo "查看完整日志请点击右上角的\"View workflow run\"" >> $GITHUB_STEP_SUMMARY

      # 20. 清理旧工作流
      - name: Cleanup old workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3

      # 21. 清理旧工件
      - name: Cleanup old artifacts
        uses: c-hive/gha-remove-artifacts@v1.4.0
        with:
          age: '7 days'

      # 22. 通知工作流状态
      - name: Notify workflow status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const jobStatus = context.job.status;
            if (jobStatus === 'success') {
              console.log('工作流运行成功');
            } else {
              console.log('工作流运行失败');
              // 这里可以添加失败通知逻辑，如发送邮件或Slack消息
            }