name: Update Multi Rules with SmartDNS
on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  push:
    branches: [ "multi" ]
    paths:
      - 'data/mod/**'
      - 'data/rules.txt'

permissions:
  contents: write
  actions: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      DATA_DIR: ${{ github.workspace }}/data
      PYTHON_SCRIPTS: ${{ github.workspace }}/data/python
      MIHOMO_BIN: ${{ github.workspace }}/data/mihomo-tool
      MAIN_BRANCH: multi
      CACHE_DIR: ${{ github.workspace }}/data/cache
      TEMP_DIR: ${{ github.workspace }}/tmp
      SMARTDNS_PORT: 5353
      SMARTDNS_RULE_SOURCES: ${{ github.workspace }}/data/smartdns_sources.txt

    steps:
      # 1. 拉取代码（multi分支）- 核心步骤
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.MAIN_BRANCH }}

      # 2. 设置Python环境- 核心步骤
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 缓存Python依赖- 核心步骤（加速依赖安装）
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. 安装系统依赖- 核心步骤（提供jq/dnsutils等工具）
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq moreutils dnsutils

      # 5. 安装Python依赖- 核心步骤（规则处理脚本依赖）
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install aiohttp aiodns psutil xxhash maxminddb pyyaml requests chardet adblockparser IPy pytz pybloom-live aiofiles

      # 6. 创建必要的目录- 修正：确保备份目录路径统一
      - name: Create directories
        run: |
          mkdir -p ${{ env.DATA_DIR }}/filter
          mkdir -p ${{ env.DATA_DIR }}/mod/backups  # 备份目录统一在mod下
          mkdir -p ${{ env.DATA_DIR }}/smartdns
          mkdir -p ${{ env.CACHE_DIR }}
          mkdir -p ${{ env.TEMP_DIR }}
          mkdir -p ${{ env.DATA_DIR }}/sources

      # 7. 下载SmartDNS（使用缓存）- 优化：缓存key依赖固定文件，避免首次失效
      - name: Install SmartDNS with cache
        id: cache-smartdns
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/smartdns
          # 依赖仓库根目录的.smartdns-cache-marker（需手动添加空文件，避免首次运行key为空）
          key: ${{ runner.os }}-smartdns-${{ hashFiles('**/.smartdns-cache-marker') }}
          restore-keys: |
            ${{ runner.os }}-smartdns-

      # 8. 如果没有缓存，下载SmartDNS（已修复版本获取问题）- 核心步骤
      - name: Download SmartDNS
        if: steps.cache-smartdns.outputs.cache-hit != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 避免API速率限制
        run: |
          echo "获取SmartDNS最新版本信息..."
          API_URL="https://api.github.com/repos/pymumu/smartdns/releases/latest"
          LATEST_RELEASE=$(curl -sL -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" $API_URL)
          
          # 检测JSON有效性
          if ! echo "$LATEST_RELEASE" | jq -e . > /dev/null 2>&1; then
              echo "错误：API响应不是有效JSON"
              echo "API响应：$LATEST_RELEASE"
              exit 1
          fi

          # 检测仓库不存在/速率限制
          RESPONSE_MSG=$(echo "$LATEST_RELEASE" | jq -r '.message // "no_message"')
          if echo "$RESPONSE_MSG" | grep -q -E "Not Found|rate limit exceeded"; then
              echo "错误：API请求失败，原因：$RESPONSE_MSG"
              exit 1
          fi

          # 提取版本标签
          RELEASE_TAG=$(echo "$LATEST_RELEASE" | jq -r '.tag_name // ""')
          if [ -z "$RELEASE_TAG" ]; then
              echo "错误：无有效tag_name"
              echo "API响应：$LATEST_RELEASE"
              exit 1
          fi
          echo "最新版本: $RELEASE_TAG"
          echo "$RELEASE_TAG" > ${{ github.workspace }}/smartdns-version.txt

          # 获取下载链接
          DOWNLOAD_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | test("smartdns-x86_64$")) | .browser_download_url' | head -n 1)
          if [ -z "$DOWNLOAD_URL" ]; then
              DOWNLOAD_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | contains("x86_64")) | .browser_download_url' | head -n 1)
          fi
          if [ -z "$DOWNLOAD_URL" ]; then
              echo "错误：未找到x86_64二进制文件"
              exit 1
          fi
          
          curl -L -o "/usr/local/bin/smartdns" --progress-bar "$DOWNLOAD_URL"
          sudo chmod +x "/usr/local/bin/smartdns"
          echo "SmartDNS安装完成"

      # 9. 并行下载规则- 核心步骤
      - name: Download rules in parallel
        run: |
          echo "开始并行下载规则..."
          python ${{ env.PYTHON_SCRIPTS }}/dl.py &
          python ${{ env.PYTHON_SCRIPTS }}/dl_smartdns.py &
          wait
          echo "规则下载完成"

      # 10. 运行merge.py（广告规则合并去重）- 核心步骤
      - name: Run merge.py
        run: |
          echo "开始合并广告规则..."
          python ${{ env.PYTHON_SCRIPTS }}/merge.py
          echo "广告规则合并完成"

      # 11. 清理临时生成的adblock和allow文件- 核心步骤
      - name: Cleanup temporary filter files
        run: |
          cd ${{ env.DATA_DIR }}/filter
          echo "清理临时文件..."
          for file in adblock*.txt; do
            if [ "$file" != "adblock_filter.txt" ] && [ "$file" != "adblock.txt" ]; then
              rm -f "$file"
            fi
          done
          for file in allow*.txt; do
            if [ "$file" != "allow_filter.txt" ] && [ "$file" != "allow.txt" ]; then
              rm -f "$file"
            fi
          done
          echo "临时文件清理完成"

      # 12. 运行SmartDNS规则清理器（带超时和重试）- 核心步骤
      - name: Run SmartDNS Rule Cleaner
        run: |
          echo "开始清理SmartDNS规则..."
          timeout 21600s python ${{ env.PYTHON_SCRIPTS }}/filter_cleaner.py || \
          (echo "第一次超时，重试..." && timeout 43200s python ${{ env.PYTHON_SCRIPTS }}/filter_cleaner.py)
          echo "SmartDNS规则清理完成"
        env:
          MAX_WORKERS: 16
          DNS_WORKERS: 100
          BATCH_SIZE: 2000
          MAX_MEMORY_PERCENT: 80
          DNS_TIMEOUT: 3
          DNS_RETRIES: 1
          USE_SMARTDNS: "true"
          PROCESS_SMARTDNS_RULES: "true"

      # 13. 并行生成多格式规则- 核心步骤
      - name: Generate multi-format rules in parallel
        run: |
          echo "开始生成多格式规则..."
          python ${{ env.PYTHON_SCRIPTS }}/filter_adg.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_adh.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_adp.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_pihole.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_hosts.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_ubo.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_clash.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_mihomo.py &
          python ${{ env.PYTHON_SCRIPTS }}/filter_smartdns.py &
          wait
          echo "多格式规则生成完成"

      # 14. 更新文档- 核心步骤
      - name: Update documentation
        run: |
          echo "更新文档..."
          python ${{ env.PYTHON_SCRIPTS }}/title.py
          python ${{ env.PYTHON_SCRIPTS }}/readme.py
          echo "文档更新完成"

      # 15. 统一清理步骤- 修正：备份目录路径与步骤6一致
      - name: Unified cleanup process
        run: |
          echo "开始统一清理..."
          # 清理备份文件（路径修正为mod/backups）
          BACKUP_DIR="${{ env.DATA_DIR }}/mod/backups"
          if [ -d "$BACKUP_DIR" ]; then
            echo "清理备份文件..."
            for type in adblock allow; do
              files=$(find "$BACKUP_DIR" -type f -name "${type}_filter_backup_*.txt" -printf '%T@ %p\n' | sort -nr)
              if [ -n "$files" ]; then
                count=$(echo "$files" | wc -l)
                if [ $count -gt 1 ]; then
                  echo "$files" | tail -n +2 | cut -d' ' -f2- | xargs -r rm -f
                  echo "删除 $((count-1)) 个旧备份文件"
                fi
              fi
            done
          fi
          
          # 清理临时目录
          rm -rf ${{ env.TEMP_DIR }}
          echo "统一清理完成"

      # 16. 提交变更- 核心步骤
      - name: Commit changes
        id: commit
        run: |
          echo "准备提交变更..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          
          if git diff --staged --quiet; then
            echo "无变更需提交"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            git commit -m "SmartDNS规则更新: [$(date +'%Y-%m-%d %H:%M:%S') UTC+8]"
          fi

      # 17. 推送变更- 优化：先判断远程差异，避免无意义merge
      - name: Push changes
        if: steps.commit.outputs.has_changes == 'true'
        run: |
          echo "开始推送变更..."
          git fetch origin ${{ env.MAIN_BRANCH }}
          
          # 仅当本地与远程有差异时才merge
          if ! git diff --quiet HEAD origin/${{ env.MAIN_BRANCH }}; then
            git merge origin/${{ env.MAIN_BRANCH }} --no-edit
            
            # 处理冲突（自动接受本地版本）
            if git diff --name-only --diff-filter=U | grep -q .; then
              echo "检测到冲突，自动解决..."
              git checkout --ours -- $(git diff --name-only --diff-filter=U)
              git add -u
              git commit -m "自动解决合并冲突"
            fi
          fi
          
          # 3次重试推送
          for i in {1..3}; do
            if git push origin ${{ env.MAIN_BRANCH }}; then
              echo "推送成功"
              break
            else
              echo "推送尝试 $i 失败，5秒后重试..."
              sleep 5
              git fetch origin ${{ env.MAIN_BRANCH }}
              ! git diff --quiet HEAD origin/${{ env.MAIN_BRANCH }} && git merge origin/${{ env.MAIN_BRANCH }} --no-edit
            fi
          done

      # 18. 创建工作流摘要- 核心步骤（便于查看运行结果）
      - name: Create workflow summary
        if: always()
        run: |
          echo "## 工作流运行摘要" >> $GITHUB_STEP_SUMMARY
          echo "- 运行状态: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- 变更提交: ${{ steps.commit.outputs.has_changes }}" >> $GITHUB_STEP_SUMMARY
          echo "## 详细日志" >> $GITHUB_STEP_SUMMARY
          echo "查看完整日志：[View workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY

      # 19. 清理旧工作流- 核心步骤（减少存储占用）
      - name: Cleanup old workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3

      # 20. 清理旧工件- 核心步骤（减少存储占用）
      - name: Cleanup old artifacts
        uses: c-hive/gha-remove-artifacts@v1.4.0
        with:
          age: '7 days'