name: Update Multi Rules with SmartDNS
on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  push:
    branches: [ "multi" ]
    paths:
      - 'data/mod/**'
      - 'data/rules.txt'
permissions:
  contents: write
  actions: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      DATA_DIR: ${{ github.workspace }}/data
      PYTHON_SCRIPTS: ${{ github.workspace }}/data/python
      MIHOMO_BIN: ${{ github.workspace }}/data/mihomo-tool
      MAIN_BRANCH: multi
      CACHE_DIR: ${{ github.workspace }}/data/cache
      TEMP_DIR: ${{ github.workspace }}/tmp
      SMARTDNS_PORT: 5353
      SMARTDNS_RULE_SOURCES: ${{ github.workspace }}/data/smartdns_sources.txt

    steps:
      # 1. 拉取代码（multi分支）
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.MAIN_BRANCH }}

      # 2. 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 安装系统依赖
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq moreutils dnsutils

      # 4. 动态安装SmartDNS (使用curl替代wget)
      - name: Install SmartDNS dynamically
        run: |
          # 获取最新发布版本信息
          echo "获取SmartDNS最新版本信息..."
          API_URL="https://api.github.com/repos/pymumu/smartdns/releases/latest"
          LATEST_RELEASE=$(curl -sL $API_URL)
          
          # 检查获取的JSON是否有效
          if echo "$LATEST_RELEASE" | jq -e '.message' | grep -q "Not Found"; then
              echo "错误：未找到仓库或发布版本，请确认项目地址"
              exit 1
          fi

          RELEASE_TAG=$(echo "$LATEST_RELEASE" | jq -r '.tag_name // empty')
          if [ -z "$RELEASE_TAG" ]; then
              echo "错误：无法获取发布标签"
              exit 1
          fi
          echo "最新版本: $RELEASE_TAG"

          # 尝试获取x86_64架构的压缩包信息
          DOWNLOAD_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | contains("x86_64-linux-all")) | .browser_download_url' | head -n 1)
          if [ -z "$DOWNLOAD_URL" ]; then
              echo "错误：未找到x86_64-linux-all架构的发布包"
              echo "可用资源："
              echo "$LATEST_RELEASE" | jq -r '.assets[].name'
              exit 1
          fi
          FILENAME=$(basename "$DOWNLOAD_URL")
          echo "下载链接: $DOWNLOAD_URL"
          echo "文件名: $FILENAME"

          # 下载并安装 (使用curl替代wget)
          echo "正在下载SmartDNS..."
          if ! curl -L -o "$FILENAME" --progress-bar "$DOWNLOAD_URL"; then
              echo "下载失败"
              exit 1
          fi

          echo "解压文件..."
          if ! tar -xzf "$FILENAME"; then
              echo "解压失败"
              exit 1
          fi
          # 解压后的目录名可能因版本而异，使用通配符匹配
          EXTRACTED_DIR=$(tar -tzf "$FILENAME" | head -1 | cut -f1 -d"/")
          if [ -z "$EXTRACTED_DIR" ]; then
              echo "无法确定解压目录"
              exit 1
          fi
          echo "解压目录: $EXTRACTED_DIR"

          cd "$EXTRACTED_DIR" || exit
          # 静态编译版本通常包含可执行文件，确认路径
          if [ -f "./smartdns/usr/sbin/" ]; then
              sudo cp -v ./smartdns /usr/local/bin/
          elif [ -f "./src/smartdns" ]; then
              sudo cp -v ./src/smartdns /usr/local/bin/
          else
              echo "错误：未找到smartdns可执行文件"
              find . -type f -name "smartdns" | head -n 5
              exit 1
          fi

          sudo chmod +x /usr/local/bin/smartdns
          cd ..
          
          # 清理
          rm -rf "$EXTRACTED_DIR" "$FILENAME"
          
          # 验证安装
          echo "SmartDNS安装完成，版本信息:"
          if /usr/local/bin/smartdns -v; then
              echo "安装成功"
          else
              echo "验证版本失败，但文件已复制"
          exit 0  # 即使-v失败也不一定代表安装完全失败，可能只是显示方式不同
        timeout-minutes: 10  # 设置步骤超时

      # 5. 安装Python依赖
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install aiohttp aiodns psutil xxhash maxminddb pyyaml requests chardet adblockparser IPy pytz pybloom-live aiofiles

      # 6. 创建必要的目录
      - name: Create directories
        run: |
          mkdir -p ${{ env.DATA_DIR }}/filter
          mkdir -p ${{ env.DATA_DIR }}/mod/backups
          mkdir -p ${{ env.DATA_DIR }}/smartdns
          mkdir -p ${{ env.CACHE_DIR }}
          mkdir -p ${{ env.TEMP_DIR }}
          mkdir -p ${{ env.DATA_DIR }}/sources

      # 7. 检测文件变更
      - name: Detect changed files
        id: changes
        uses: tj-actions/changed-files@v42
        with:
          files: |
            data/mod/**
            data/rules.txt

      # 8. 运行dl.py（下载规则）
      - name: Run dl.py
        run: |
          cd ${{ github.workspace }}
          python ${{ env.PYTHON_SCRIPTS }}/dl.py

      # 9. 运行SmartDNS规则下载器
      - name: Download SmartDNS rules
        run: |
          cd ${{ github.workspace }}
          python ${{ env.PYTHON_SCRIPTS }}/dl_smartdns.py

      # 10. 运行merge.py（广告规则合并去重）
      - name: Run merge.py
        run: |
          cd ${{ github.workspace }}
          python ${{ env.PYTHON_SCRIPTS }}/merge.py
          echo "广告规则合并完成"

      # 11. 运行SmartDNS规则清理器
      - name: Run SmartDNS Rule Cleaner
        run: |
          cd ${{ github.workspace }}
          python ${{ env.PYTHON_SCRIPTS }}/filter_cleaner.py
        env:
          MAX_WORKERS: 8
          DNS_WORKERS: 30
          BATCH_SIZE: 500
          MAX_MEMORY_PERCENT: 80
          DNS_TIMEOUT: 8
          DNS_RETRIES: 2
          USE_SMARTDNS: "true"
          PROCESS_SMARTDNS_RULES: "true"

      # 12. 生成多格式规则
      - name: Generate multi-format rules
        run: |
          cd ${{ github.workspace }}
          python ${{ env.PYTHON_SCRIPTS }}/filter_adg.py
          python ${{ env.PYTHON_SCRIPTS }}/filter_adh.py
          python ${{ env.PYTHON_SCRIPTS }}/filter_adp.py
          python ${{ env.PYTHON_SCRIPTS }}/filter_pihole.py
          python ${{ env.PYTHON_SCRIPTS }}/filter_hosts.py
          python ${{ env.PYTHON_SCRIPTS }}/filter_ubo.py
          python ${{ env.PYTHON_SCRIPTS }}/filter_clash.py
          python ${{ env.PYTHON_SCRIPTS }}/filter_mihomo.py
          python ${{ env.PYTHON_SCRIPTS }}/filter_smartdns.py

      # 13. 更新文档
      - name: Update documentation
        run: |
          cd ${{ github.workspace }}
          python ${{ env.PYTHON_SCRIPTS }}/title.py
          python ${{ env.PYTHON_SCRIPTS }}/readme.py

      # 14. 提交变更
      - name: Commit changes
        id: commit
        run: |
          cd ${{ github.workspace }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            git commit -m "SmartDNS规则更新: [$(date +'%Y-%m-%d %H:%M:%S') UTC+8]"
          fi

      # 15. 推送变更
      - name: Push changes
        if: steps.commit.outputs.has_changes == 'true'
        run: |
          cd ${{ github.workspace }}
          for i in 1 2 3; do
            git pull --rebase origin ${{ env.MAIN_BRANCH }}
            git push origin ${{ env.MAIN_BRANCH }} && break || sleep 5
          done

      # 16. 清理旧工作流
      - name: Cleanup old workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3

      # 17. 清理旧工件
      - name: Cleanup old artifacts
        uses: c-hive/gha-remove-artifacts@v1.4.0
        with:
          age: '7 days'

      # 18. 清理临时目录
      - name: Cleanup temporary files
        run: |
          rm -rf ${{ env.TEMP_DIR }}
          echo "临时文件清理完成"